[package]
name = "markdialog"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "built_res", # Built Resources
    "player",    # Dialog Player
    "converter"  # Markdown Converter
]

[dependencies]
built_res = { path = "built_res" }
markdialog_player = { path = "player" }
markdialog_converter = { path = "converter" }
